USE [MASTER]
GO

--SCRIPT DE CRIAÇÃO DO LOGON PARA ACESSAR A INSTANCIA

CREATE LOGIN [NOME_LOGON] WITH PASSWORD=N'SENHA_FORNECIDA',
DEFAULT_DATABASE=[BASE_PADRAO], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

--ALTERANDO A ROLE DO LOGIN CRIADO 

ALTER ROLE [ROLE NIVEL DE INSTANCIA] ADD MEMBER [NOME_LOGON]
GO

USE [BASE_DE_DADOS_PADRAO]
GO

--CRIANDO O USUÁRIO NA BASE DE DADOS  

CREATE USER [NOME_USUARIO] FOR LOGIN [NOME_LOGON]
GO

--ALTERANDO A ROLE DO USUÁRIO 

USE [BASE_DE_DADOS_PADRAO]
GO

ALTER ROLE [ROLE NIVEL DE DB] ADD MEMBER [NOME_USUARIO]
GO


--EXEMPLO UTILIZANDO A BASE DE DADOS AdventureWorks2022

USE [master]
GO
CREATE LOGIN [teste] WITH PASSWORD=N'Teste@123', DEFAULT_DATABASE=[AdventureWorks2022], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [AdventureWorks2022]
GO
CREATE USER [teste] FOR LOGIN [teste]
GO
USE [AdventureWorks2022]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [teste]
GO
ALTER ROLE [db_reader] ADD MEMBER [teste]
GO
