--Monitorar o espaço em disco

 SELECT DISTINCT
        VS.VOLUME_MOUNT_POINT [MONTAGEM] ,
        VS.LOGICAL_VOLUME_NAME AS [VOLUME] ,
        CAST(CAST(VS.TOTAL_BYTES AS DECIMAL(19, 2)) / 1024 / 1024 / 1024 AS DECIMAL(10, 2)) AS [ESPAÇO_TOTAL_GB] ,
        CAST(CAST(VS.AVAILABLE_BYTES AS DECIMAL(19, 2)) / 1024 / 1024 / 1024 AS DECIMAL(10, 2)) AS [TAMANHO_DISPONIVEL_GB] ,
        CAST(( CAST(VS.AVAILABLE_BYTES AS DECIMAL(19, 2)) / CAST(VS.TOTAL_BYTES AS DECIMAL(19, 2)) * 100 ) AS DECIMAL(10, 2)) AS [PERC_DISPONIVEL] ,
        CAST(( 100 - CAST(VS.AVAILABLE_BYTES AS DECIMAL(19, 2)) / CAST(VS.TOTAL_BYTES AS DECIMAL(19, 2)) * 100 ) AS DECIMAL(10, 2)) AS [PERC_UTILIZADO]
    FROM
        SYS.MASTER_FILES AS MF
        CROSS APPLY [SYS].[DM_OS_VOLUME_STATS](MF.DATABASE_ID, MF.FILE_ID) AS VS
